language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS=slopespot.config.TestingConfig
    - DATABASE_URL=postgresql://localhost/slopespot_test


install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database slopespot_test;' -U postgres
  - python manage.py db upgrade

# command to run tests
script: py.test
