language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch

services:
  - postgresql

env:
    - APP_SETTINGS=slopespot.config.TestingConfig
    - DATABASE_URL=postgresql://localhost/slopespot_test


install: "pip install -r requirements.txt"


before_script:
  - psql -c 'create database slopespot_test;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

# command to run tests
script: py.test
