language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  
# command to install dependencies
before_install:
    - 'pip install virtualenv'
    - 'virtualenv env'
    - 'source env/bin/activate'
    
install: "pip install -r requirements.txt"

# command to run tests
script: py.test